### ISSUE TITLE
Lien manquant vers la page d'accueil

### ISSUE THREAD

**Issue by elnikoff-t** [NotANameServer/Not-a-Hub#23]
Lorsqu'on est sur un des articles sur [la page d'accueil](https://hub.notaname.fr/), il n'existe aucun moyen de revenir au niveau de l'arborescence principale du site.

C'est un peu gênant pour la navigation.

**Comment by Julien00859** [comment]
Il faudrait voir si c'est possible de configurer le thème pour qu'il le fasse de lui-même, @Mesteery tu aurais une idée ? Sinon l'alternative, on modifie les billets pour ajouter le nécessaire en tête de chaque article.

**Comment by Equinox4** [comment]
Si on peut pas le gérer avec le thème, peut-être ajouter une fonction dans index.py qui ajoute automatiquement un lien vers la page d'accueil au début de l'article ?
(par contre on va peut-être devoir éditer les articles existant à la main)

**Comment by Mesteery** [comment]
Il n'y a aucune option pour un retour à l'accueil dans la configuration du thème. Mais faire comme @Equinox4 propose serait la meilleure solution je pense

**Comment by Equinox4** [comment]
Update: on a trouvé le moyen de modifier le thème, du coup je pense qu'on va simplement ajouter un lien dedans.
