### ISSUE TITLE
Proposition de liens

### ISSUE THREAD

**Issue by arkena00** [NotANameServer/Not-a-Hub#3]
Coucou
On pourrait faire les suggestions de ressources via des issues, plutôt que de passer directement par des PR ?
Exemple : 

Type : Tuto
Format : Vidéo
Tags : game-dev, UE4, animation
Langue : FR
Lien : https://www.youtube.com/watch?v=MgujyPVJfL0

Ce qui permet ensuite de discuter de la suggestion avant de l'ajouter, et c'est plus simple et rapide à faire pour ceux qui veulent juste faire une suggestion sans se demander ou mettre les infos, comment respecter le bon format etc ..

**Comment by Equinox4** [comment]
Pourquoi pas, c'est effectivement plus léger qu'une PR.

**Comment by arkena00** [comment]
Faut ajouter un template alors :p

**Comment by Equinox4** [comment]
oui, j'ai close parce qu'on l'a précisé dans contributing, mais on peut aussi ajouter un template.

**Comment by Equinox4** [comment]
du coup je réouvre jusqu'a ce que ça soit mis en place

**Comment by Equinox4** [comment]
cf #28

**Comment by Elanis** [comment]
Template ajouté, si vous pensez qu'il en manque d'autres, n'hesitez pas à ouvrir d'autres issues/PR.
