### ISSUE TITLE
Référencer le site not a hub sur google

### ISSUE THREAD

**Issue by luc-git** [NotANameServer/Not-a-Hub#46]
Il est possible de demander à google de gratuitement indexer une page grâce à ça

https://support.google.com/webmasters/answer/9012289?hl=fr#request_indexing

**Comment by Equinox4** [comment]
En principe il n'est pas nécessaire de faire cette opération manuellement, le site contient toutes les méta-données nécessaire pour une indexation correcte par les bots de google.
D'ailleurs en tapant "not a hub" dans la barre de recherche, le premier lien qui est affiché c'est celui de ce dépôt.

**Comment by luc-git** [comment]
C'est vrai mais c'est dommage que ce ne soit pas celui du site directement

**Comment by luc-git** [comment]
Mais du coup pourquoi il n'a pas été indexé?

**Comment by luc-git** [comment]
Je ne vois pas de robot.txt

**Comment by Equinox4** [comment]
le site est indexé mais il ne s'appelle pas "not a hub", l'url c'est hub.notaname.fr, cela peut expliquer qu'il n'apparaisse pas quand on cherche "not a hub".
les moteurs de recherche semblent accorder un poids plus importants aux résultats dont l'url match la requête plutôt que le nom du site

**Comment by Elanis** [comment]
Il est indexé si on cherche direct avec "hub.notaname.fr", il est juste mal ranké du coup :)

**Comment by Equinox4** [comment]
yep, et il existe beaucoup d'autres sites avec un nom similaire, ou des utilisateurs de réseaux sociaux qui porte le nom "notaname" donc je pense pas qu'on puisse améliorer le ranking facilement
