### ISSUE TITLE
Python IDE - Atom is no longer supported

### ISSUE THREAD

**Issue by luc-git** [NotANameServer/Not-a-Hub#59]
### URL de l'article concerné

https://hub.notaname.fr/langages/python/programmer-en-python-quel-ide-choisir

### À propos de cet article

https://github.com/NotANameServer/Not-a-Hub/blob/ffde5554aed26ec432b76a6c523fa4b0dcbda393/langages/python/programmer-en-python-quel-ide-choisir.md?plain=1#L25

Y a un petit soucis c’est que atom n’est plus du tout supporté. Faudrait peut-être ajouter « abandonné » ou « plus maintenu » dans le con. Sinon le retirer de la liste serait dommage.

**Comment by Equinox4** [comment]
en effet, il faudrait faire un addendum avec ce lien: https://github.blog/2022-06-08-sunsetting-atom/
(atom.io redirige dessus)
