### ISSUE TITLE
[NOUVEL ARTICLE] Bot discord en python

### ISSUE THREAD

**Issue by Sergeileduc** [NotANameServer/Not-a-Hub#61]
### Sujet de l'article

Hello la team NaN

ça vous intéresserait, que j'écrive un truc de base pour les bots discords en python ?
(un dossier python dans le dossier "bots-discord")
avec dedans, un premier truc simple (en 1 seul fichier)
et après, un truc un peu plus avancé, avec des "cogs" (des fichiers que tu importes pour regrouper tes commandes en gros) ?
rien de très fancy, mais un début quoi.

?

**Comment by Equinox4** [comment]
Hello, pourquoi pas, il y a une forte demande concernant la réalisation de bots discord (pas seulement en python), si tu pouvais écrire un article établissant quelques règles et conseils simples pour correctement structurer un programme de ce type je pense que ça serait intéressant.
Il faudrait que l'article ne soit pas trop focalisé sur le langage mais plutôt sur l'architecture d'un projet type de bot discord (tu pourras brièvement justifier le choix du python éventuellement)

**Comment by Sergeileduc** [comment]
Alors je pensais plus partir sur des exemples de codes "clé en main"
(avec des commentaires bien sûr)

je peux soumettre un premier jet, vous me direz ?

mi article / mi code prêt à l'emploi quoi

**Comment by Equinox4** [comment]
fais donc

**Comment by Equinox4** [comment]
up @Sergeileduc ?

**Comment by Sergeileduc** [comment]
je ferais ça dans la semaine, je pense

**Comment by Sergeileduc** [comment]
PR #64 is a start for that
