### ISSUE TITLE
[NOUVEL ARTICLE] Les arrays de Php sont-ils vraiment des arrays ?

### ISSUE THREAD

**Issue by HellperKK** [NotANameServer/Not-a-Hub#79]
### Sujet de l'article

Bonjour, 

Je souhaite écrire un article sur le type array de php et le fait qu'il s'agit plutôt d'une forme de dictionnaire. L'idée vient notamment du fait d'un utilisateur qui dans le salon javascript pensais par confusion que les objets de js étaient des arrays.

Mon plan actuel de l'article serait sous cette forme:

- présentation de l'array php.
- présentation des trois types "majeurs" de collection (tableau, tableau associatif et set) dans une approche plus d’algorithmie (language agnostic).
- mise en correspondance de l'array php et des définitions précédentes.
- conclusion par une revue de différentes fonctions qui manipulent des array et qui les traitent ou non comme de réels arrays.

Il s'agira donc plutôt d'un article destiné aux débutants avec la question des arrays php comme partiellement prétexte pour revoir les collections :)

**Comment by Equinox4** [comment]
Excellente idée, d'autant plus que je m'étais interressé au sujet il y a qq temps (quand peuk avait link un article sur php à review sur zds), je relirai cet article avec grand plaisir :)
